server:
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true

spring:
  config:
    import: optional:file:.env[.properties]

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
    persist-authorization: true
    display-request-duration: true
    default-models-expand-depth: 2

spotify:
  client-id: ${SPOTIFY_CLIENT_ID}
  client-secret: ${SPOTIFY_CLIENT_SECRET}
  api-base-url: https://api.spotify.com/v1
  accounts-base-url: https://accounts.spotify.com
